directory: /data/music
library: /data/musiclibrary.db

paths:
  default: Albums/%title{$albumartist}/$album%aunique{}/$track $title
  singleton: Singles/%title{$artist}/$title
  comp: Compilations/$album%aunique{}/$track $title

plugins:
  - webrouter
  - web
  - webm3u
  - beetstream
  - aura
  - smartplaylist

webrouter:
  routes:
    /:
      plugin: web
    /favicon.ico:
      plugin: webrouter.favicon
    /subsonic:
      plugin: beetstream
      config:
        never_transcode: true
    /aura:
      plugin: aura
      blueprint: aura_bp
    /m3u:
      plugin: webm3u

aura:
  page_limit: 100

smartplaylist:
  auto: false
  output: m3u
  playlist_dir: /data/playlists
  relative_to: /data/playlists
  playlists:
  - name: all.m3u
    query: ''
